name: Upload S3
description: 'Upload directory to S3'
author: 'Dong Keon Kim'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  aws-key-id:
    description: 'aws key id'
    required: true
  aws-secret-access-key:
    description: 'aws secret access key'
    required: true
  aws-bucket:
    description: 'aws bucket name'
    required: true
  path:
    required: true
    description: 'path(s) to upload'
  destination-path:
    required: false
    default: /
    description: 'destination directory for upload'
  use-relative-path:
    required: false
    default: false
    description: 'include relative filesystem path in S3 bucket path'
outputs:
  object_key:
    description: 'object key'
  object_locations:
    description: 'object locations'
runs:
  using: 'node16'
  main: 'dist/index.js'
